---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-s3-driver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-s3-driver
  template:
    metadata:
      labels:
        app: csi-s3-driver
    spec:
      serviceAccount: csi-s3-driver-sa
      containers:
        - name: s3-plugin
          image: {{ .Values.global.image }}:{{ .Values.global.tag }}
          imagePullPolicy: Always
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeId=$(NODE_ID)
            - --v=5
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.minio.accessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.minio.accessSecret }}
            - name: ENDPOINT_URL
              value: {{ .Values.minio.url }}
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: liveness-probe
          image: xwharbor.wxchina.com/cpaas-pub/sig-storage/livenessprobe:v2.12.0
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=29652
            - --v=5
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              cpu: 1000m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        #Sidecar: csi-provisione
        - name: csi-provisioner
          image: xwharbor.wxchina.com/cpaas-pub/sig-storage/csi-provisioner:v4.0.0
          imagePullPolicy: Always
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--leader-election-namespace={{ .Release.Namespace }}"
            - "--extra-create-metadata=true"
            - "--timeout=1200s"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              cpu: 100m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: socket-dir
          emptyDir: {}