apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-s3fs-sc
provisioner: minio.s3.csi.xw.com
parameters:
  mounter: s3fs
  bucket: k8s-dev-sc-130
  access-key: {{ .Values.minio.accessKey }}
  secret-key: {{ .Values.minio.accessSecret }}
  endpoint: {{ .Values.minio.url }}